// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	fish_api "fish_net/cmd/api/biz/router/fish_api"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	fish_api.Register(r)
}
