// Code generated by hertz generator.

package main

import (
	handler "fish_net/cmd/api/biz/handler"
	webauthnApi "fish_net/cmd/api/biz/handler/auth"

	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)

	v1 := r.Group("/v1")
	{
		// auth
		auth := v1.Group("/auth")
		auth.GET("/register/begin/:username", webauthnApi.RegisterBegin)
		auth.POST("/register/finish/:id", webauthnApi.RegisterFinish)
		auth.GET("/login/begin/:username", webauthnApi.LoginBegin)
		auth.POST("/login/finish/:id", webauthnApi.LoginFinish)
		// user
	}
	// your code ...
}
