// Code generated by hertz generator.

package fish_api

import (
	"context"

	fish_api "fish_net/cmd/api/biz/model/fish_api"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// CreateUser .
// @router /v2/user/register [POST]
func CreateUser(ctx context.Context, c *app.RequestContext) {
	var err error
	var req fish_api.CreateUserRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(fish_api.CreateUserResponse)

	c.JSON(consts.StatusOK, resp)
}

// CheckUser .
// @router /v2/user/login [POST]
func CheckUser(ctx context.Context, c *app.RequestContext) {
	var err error
	var req fish_api.CheckUserRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(fish_api.CheckUserResponse)

	c.JSON(consts.StatusOK, resp)
}

// CreateNote .
// @router /v2/note [POST]
func CreateNote(ctx context.Context, c *app.RequestContext) {
	var err error
	var req fish_api.CreateNoteRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(fish_api.CreateNoteResponse)

	c.JSON(consts.StatusOK, resp)
}

// QueryNote .
// @router /v2/note/query [GET]
func QueryNote(ctx context.Context, c *app.RequestContext) {
	var err error
	var req fish_api.QueryNoteRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(fish_api.QueryNoteResponse)

	c.JSON(consts.StatusOK, resp)
}

// UpdateNote .
// @router /v2/note/:note_id [PUT]
func UpdateNote(ctx context.Context, c *app.RequestContext) {
	var err error
	var req fish_api.UpdateNoteRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(fish_api.UpdateNoteResponse)

	c.JSON(consts.StatusOK, resp)
}

// DeleteNote .
// @router /v2/note/:note_id [DELETE]
func DeleteNote(ctx context.Context, c *app.RequestContext) {
	var err error
	var req fish_api.DeleteNoteRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(fish_api.DeleteNoteResponse)

	c.JSON(consts.StatusOK, resp)
}
