#!/usr/bin/env bash

regex="^(feat|fix|docs|chore|style|refactor|test|workflow|build|ci)(\(\w+\))?: ((.){3,50})"

COMMIT_MSG=$(grep -E "$regex" <"$1")

if [ -n "$COMMIT_MSG" ]; then
    exit 0
fi

regex_m="^(Merge)"

COMMIT_MSG=$(grep -E "$regex_m" <"$1")

if [ -n "$COMMIT_MSG" ]; then
    exit 0
fi

echo "Commit Message 不规范，请修改!"
echo "正则匹配规则: [$regex]"
echo "your commit msg: [$(cat "$1")]"
exit 1
